FROM blauerberg/drupal-php:7.3-apache
# Install packages
RUN rm /bin/sh && ln -s /bin/bash /bin/sh && \
    apt-get update && apt-get install --no-install-recommends -y \
    curl \
    wget \
    vim \
    git \
    unzip \
    mariadb-client && \
    apt-get clean && rm -rf /var/lib/apt/lists/*


RUN composer global remove drush/drush && \
    composer global require drush/drush:7.* -W && \
    composer global require "pear/console_table" "v1.3.1 as v1.2.99" && \
    composer global update

